# Site settings
title: The Obama Legacy Project
subtitle: by Presente Action
email: info@presente.org
description: The Obama Legacy Project is a campaign led by Presente.org in partnership with grassroots and human rights organizations and their allies nationwide who want to raise awareness about President Obama’s legacy on immigration.

#baseurl:

baseurl: https://presente.github.io/olegacy/
url: https://presente.github.io/olegacy/
# the base hostname & protocol for your site

author:
street_address: 1330 Broadway, Suite 300
city: Oakland
state: CA
zip_code: 94612
country: United States of America
# phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7

# Social settings
500px_url:
facebook_url: https://www.facebook.com/Presente.org/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/presenteorg

# Build settings
markdown: kramdown
